## application.yml para microservicio user-service
server:
  port: 8086

spring:
  application:
    name: bs-user-management-v1

  datasource:
    url: jdbc:mariadb://localhost:3306/db_user
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  ##datasource:
  ##  driverClassName: org.postgresql.Driver
  ##  url: jdbc:postgresql://localhost:5432/usersDb
  ##  username: admin
  ##  password:
  ##jpa:
  ##  hibernate:
  ##    ddl-auto: create
  ##  database: postgresql
  ##  database-platform: org.hibernate.dialect.PostgreSQLDialect
  ##  defer-datasource-initialization: true